config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'

  get '/about'            =>  'static_pages#about'
  get '/retailer_info'    =>  'static_pages#retailer_info'
  get '/experience'       =>  'static_pages#experience'
  get '/decal'            =>  'static_pages#decal'
  get '/relaunch'         =>  'static_pages#relaunch'
  get '/join_confirmation'=>  'static_pages#join_confirmation'
  get '/confirmation_required'  => 'static_pages#confirmation_required'

  post 'swipe_styles/invite'    => 'swipe_styles#invite'
  get 'swipe_styles/new'        => 'swipe_styles#new'
  get 'swipe_styles/results'    => 'swipe_styles#results'
  post 'swipe_styles/like'      => 'swipe_styles#like'
  post 'swipe_styles/complete'  => 'swipe_styles#complete'
  delete 'swipe_styles/destroy' => 'swipe_styles#destroy'
  post 'swipe_styles/update_matches' => 'swipe_styles#update_matches'
  post 'swipe_styles/update_style_needs' => 'swipe_styles#update_style_needs'

  resources :share_quizzes, param: :name, only: [:show]

  namespace :webhooks do
    get 'mailchimp/subscribe'  => 'mailchimp_importer#validate'
    post 'mailchimp/subscribe' => 'mailchimp_importer#subscribe'
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  scope module: 'users' do
    resources :users, only: [] do
      collection do
        get :shoppers
      end
    end
  end

  resources :style_profiles, only: [:edit, :update, :new, :create] do
    collection do
      post :quickstart
    end
  end

  resources :retailers, only: [:show, :index, :new, :create] do
    member do
      get 'scheduled_availabilities'
      get 'enable_available_dates'
      get 'enable_available_times'
      get 'show_drop_in_location'
      get 'press_kit'
    end
  end

  resources :drop_ins, only: [:create, :update, :destroy] do
    member do
      patch :cancel
    end
    collection do
      get :upcoming
    end
  end

  resources :drop_in_availabilities, only: [:create, :update] do
    collection do
      get :personal
    end
  end

  get 'drop_in_availabilities/apply_form' => 'drop_in_availabilities#apply_form'

  resources :reports, only: [:new, :create]

  resources :retailer_referrals, only: [:create]

end

app/models/drop_in.rb
class DropIn < ActiveRecord::Base
  Time::DATE_FORMATS[:month_slash_day] = "%_m#{'/'}%d"
  Time::DATE_FORMATS[:informal_time] = "%l:%M %p"

  ACTIVE_STATE = 1
  CANCELED_STATE = 0

  belongs_to :retailer
  belongs_to :user

  validate :retailer_available_for_drop_in, on: :create
  validate :shopper_drop_in_at_same_time
  validates :retailer_id, presence: true
  validates :user_id, presence: true
  validates :time, presence: true
  validates :comment, length: {maximum: 250}
  validates :shopper_rating, numericality: { greater_than_or_equal_to: 1, 
                                             less_than_or_equal_to: 5 }, 
                             unless: "shopper_rating.blank?"
  validates :retailer_rating, numericality: { greater_than_or_equal_to: 1, 
                                             less_than_or_equal_to: 5 }, 
                             unless: "retailer_rating.blank?"
  validates :shopper_feedback, length: { maximum: 500 }
  validates :retailer_feedback, length: { maximum: 500 }
  validates :sales_generated, numericality: true, unless: "sales_generated.blank?"

  default_scope { order('time DESC') }

  scope :overlapping, ->(start_time, end_time) { where("time >= ? and time < ?", start_time, end_time) }

  after_create do
    ShopperMailer.upcoming_styling_reminder(self).deliver_later(wait_until: time - 30.minutes)
    ShopperMailer.after_styling_reminder(self).deliver_later(wait_until: time + 1.hour)
    RetailUserMailer.upcoming_styling_reminder(self).deliver_later(wait_until: time - 30.minutes)
    RetailUserMailer.after_styling_reminder(self).deliver_later(wait_until: time + 1.hour)
  end

  def retailer_available_for_drop_in
    unless retailer.nil? || time.nil?
      unless retailer.available_for_drop_in?(time)
        errors.add(:time, "is not an available time slot for a drop in")
      end
    end
  end

  def shopper_drop_in_at_same_time
    unless user_id.nil? || time.nil?
      same_time_drop_in = DropIn.where(user_id: user_id, time: time).first
      unless same_time_drop_in.nil?
        if same_time_drop_in.id != self.id
          errors[:base] << "You have another drop-in scheduled at this time"
        end
      end
    end
  end

  def self.upcoming_for_shopper user_id
    where("user_id = ? and time > ?", user_id, Time.zone.now)
  end

  def self.upcoming_for_retailer retailer_id
    where("retailer_id = ? and time > ?", retailer_id, Time.zone.now)
  end

  def self.previous_for_shopper user_id
    where("user_id = ? and time < ?", user_id, Time.zone.now)
  end

  def self.previous_for_retailer retailer_id
    where("retailer_id = ? and time < ?", retailer_id, Time.zone.now)
  end

  def self.upcoming_for_shopper_at_retailer user_id, retailer_id
    where("user_id = ? and retailer_id = ? and time > ?",
                          user_id, retailer_id, Time.zone.now)
  end

  def colloquial_time
    if time.to_date == Time.zone.today
      date_string = "Today"
    elsif time.to_date == Time.zone.today + 1.day
      date_string = "Tomorrow"
    else
      date_string = time.to_s(:month_slash_day)
    end

    time_string = time.to_s(:informal_time)

    "#{date_string} @ #{time_string}".gsub(":00",'')
  end

  def canceled?
    status == CANCELED_STATE
  end

  def ics_attachment type
    description = 'Personal Styling Session'
    description << " with #{retailer.name}" if type == :shopper
    description << " for #{user.first_name}" if type == :retailer
    cal = Icalendar::Calendar.new
    cal.timezone do |t|
      t.tzid = "America/New_York"

      t.daylight do |d|
        d.tzoffsetfrom = "-0500"
        d.tzoffsetto   = "-0400"
        d.tzname       = "EDT"
        d.dtstart      = "19700308T020000"
        d.rrule        = "FREQ=YEARLY;BYMONTH=3;BYDAY=2SU"
      end

      t.standard do |s|
        s.tzoffsetfrom = "-0400"
        s.tzoffsetto   = "-0500"
        s.tzname       = "EST"
        s.dtstart      = "19701101T020000"
        s.rrule        = "FREQ=YEARLY;BYMONTH=11;BYDAY=1SU"
      end
    end
    cal.event do |e|
      e.dtstart     = Icalendar::Values::DateTime.new time, 'tzid' => 'America/New_York'
      e.dtend       = Icalendar::Values::DateTime.new (time + 30.minutes), 'tzid' => 'America/New_York'
      e.location    = StreetAddress::US.parse(retailer.location.address).to_s
      e.summary     = 'OpenStile-Styling Session'
      e.description = description
      e.organizer = Icalendar::Values::CalAddress.new("mailto:info@openstile.com", cn: 'OpenStile')
      e.ip_class    = "PRIVATE"
    end

    cal
  end
end

app/controllers/drop_ins_controller.rb
class DropInsController < ApplicationController

  before_filter :store_shopper_location
  before_filter :authenticate_user!, except: [:create]
  before_action :correct_drop_in_customer, only: [:update]
  before_action :correct_drop_in_shopper, only: [:destroy, :cancel]

  def create
    retrieved_params = drop_in_params
    selected_date = retrieved_params.delete(:selected_date)
    selected_time = retrieved_params.delete(:selected_time)
    unless (selected_date.blank? || selected_time.blank?)
      datetime = ActiveSupport::TimeZone[Time.zone.name]
                    .parse("#{selected_date} #{selected_time}")
      retrieved_params[:time] = datetime
    end

    if retrieved_params[:user_id].blank?
      store_signed_out_booking retrieved_params.compact
      flash[:warning] = "Please log in or create an account so that we can save your booking."
      redirect_to new_user_session_path
    else
      @drop_in = DropIn.new(retrieved_params)

      if @drop_in.save
        RetailUserMailer.drop_in_scheduled_email(@drop_in).deliver_later
        ShopperMailer.drop_in_scheduled_email(@drop_in).deliver_later
        AdminMailer.drop_in_scheduled(@drop_in).deliver_later unless User.admins.empty?
        flash[:success] = "Your drop-in was scheduled! The retailer will be notified."
        redirect_to upcoming_drop_ins_path
      else
        @retailer = @drop_in.retailer
        render 'retailers/show'
      end
    end
  end

  def update
    if @drop_in.update_attributes(drop_in_params)
      flash[:success] = "Your drop-in was updated!"
      redirect_to upcoming_drop_ins_path
    else
      flash[:danger] = "There was an unexpected error updating your drop-in."
      redirect_to root_path
    end
  end

  def destroy
    RetailUserMailer.drop_in_canceled_email(@drop_in).deliver_later
    ShopperMailer.drop_in_canceled_email(@drop_in).deliver_later
    @drop_in.destroy
    flash[:success] = "Drop in cancelled. Retailer will be notified"
    redirect_to upcoming_drop_ins_path
  end

  def cancel
    RetailUserMailer.drop_in_canceled_email(@drop_in).deliver_later
    ShopperMailer.drop_in_canceled_email(@drop_in).deliver_later
    if @drop_in.update_attribute(:status, DropIn::CANCELED_STATE)
      flash[:success] = "Your styling session has been canceled. Retailer will be notified"
      redirect_to upcoming_drop_ins_path
    else
      flash[:danger] = "There was an unexpected error cancelling your styling session."
      redirect_to root_path
    end
  end

  def upcoming
    if current_user.user_role.name == UserRole::SHOPPER
      @drop_ins = DropIn.where(user: current_user)
    elsif current_user.user_role.name == UserRole::RETAILER
      @drop_ins = DropIn.where(retailer: current_user.retailer)
    else
      flash[:danger] = "Unexpected error"
      redirect_to root_path
    end
  end

  private
    def correct_drop_in_shopper
      @drop_in = DropIn.find(params[:id])
      redirect_to root_url unless (@drop_in.user == current_user && current_user.user_role.name == UserRole::SHOPPER)
    end

    def correct_drop_in_customer
      @drop_in = DropIn.find(params[:id])
      if current_user.user_role.name == UserRole::SHOPPER
        redirect_to root_url unless (@drop_in.user == current_user)
      elsif current_user.user_role.name == UserRole::RETAILER
        redirect_to root_url unless (@drop_in.retailer == current_user.retailer)
      else
        redirect_to root_url
      end
    end

    def drop_in_params
      params.require(:drop_in).permit(:user_id, :retailer_id, :comment,
                          :shopper_rating, :shopper_feedback, :sales_generated,
                          :retailer_rating, :retailer_feedback,
                          :selected_date, :selected_time)
    end
end

app/helpers/drop_ins_helper.rb
module DropInsHelper
end

app/views/drop_ins/_previous_for_retail_user.html.erb
<div class="content">
  <div class="col-xs-3">
    <h3><%= drop_in.user.first_name %></h3>
    <h3><%= drop_in.colloquial_time %></h3>
  </div>
  <div class="col-xs-5">
    <div class="edit-rating">
      <%= link_to '[edit]', '#', data: {drop_in_id: drop_in.id } %>
    </div>
    <div class="rating-summary">
      <div class="star-rating row">
        <%= render 'star_rating', rating: drop_in.retailer_rating %>
      </div>
      <h4><%= ("$%6.2f" % drop_in.sales_generated) unless drop_in.sales_generated.nil? %></h4>
      <h4><%= drop_in.retailer_feedback %></h4>
    </div>
    <div class="rating-form">
      <%= form_for drop_in, html: {class: "form-horizontal"} do |f| %>
          <div class="form-group">
            <%= f.label :retailer_rating, "Rating", class: "control-label" %>
            <%= f.select :retailer_rating, (1..5).map{|v| ["#{v} out of 5", v] },
                         {},
                         class: "form-control",
                         prompt: true %>
          </div>

          <div class="form-group">
            <%= f.label :sales_generated, "How much did the shopper spend?", class: "control-label" %>
            <div class="input-group">
              <span class="input-group-addon">$</span>
              <%= f.text_field :sales_generated, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :retailer_feedback, "Feedback", class: "control-label" %>
            <%= f.text_area :retailer_feedback, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit 'Save', class: 'btn btn-default' %>
          </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-4 text-center">
    <h1>
      <i class="show-preferences-toggle fa fa-caret-right"></i>
    </h1>
  </div>
  <div class="col-xs-8 col-xs-offset-2 preferences-details">
    <%= render 'shared/style_preferences',
               profile: drop_in.user.style_profile %>
  </div>
</div>

app/views/drop_ins/_previous_for_shopper.html.erb
<div class="content">
  <div class="col-xs-2 text-center edit-rating">
    <%= link_to '[edit]', '#', data: {drop_in_id: drop_in.id } %>
  </div>
  <div class="col-xs-10">
    <h3><%= link_to drop_in.retailer.name, retailer_path(drop_in.retailer)%></h3>
    <h4><%= drop_in.colloquial_time %></h4>
    <div class="rating-summary">
      <div class="star-rating row">
        <%= render 'star_rating', rating: drop_in.shopper_rating %>
      </div>
      <h4><%= drop_in.shopper_feedback %></h4>
    </div>
    <div class="rating-form col-xs-6">
      <%= form_for drop_in, html: {class: "form-horizontal"} do |f| %>
          <div class="form-group">
            <%= f.label :shopper_rating, "Rating", class: "control-label" %>
            <%= f.select :shopper_rating, (1..5).map{|v| ["#{v} out of 5", v] },
                         {},
                         class: "form-control",
                         prompt: true %>
          </div>

          <div class="form-group">
            <%= f.label :shopper_feedback, "Feedback", class: "control-label" %>
            <%= f.text_area :shopper_feedback, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit 'Save', class: 'btn btn-default' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/drop_ins/_sample_booking_for_retailer.html.erb
<div class="row">
  <div class="single-booking col-xs-10 col-xs-offset-1">
    <div class="content">
      <div class="col-xs-7 col-xs-offset-2">
        <h3>Jane (Sample) </h3>
        <h3>Tomorrow @ 11AM</h3>
        <h4>"Need to find something chic for my company's holiday party"</h4>
      </div>
      <div class="col-xs-3">
        <h1>
          <i class="show-preferences-toggle fa fa-caret-right"></i>
        </h1>
      </div>
      <div class="col-xs-8 col-xs-offset-2 preferences-details">
        <h3>Tops</h3>
        <ul>
          <li>Sizes: <%= TopSize.all.sample.name %></li>
          <li>Budget: max $50</li>
          <li>Fit: <%= TopFit.all.sample.name %></li>
        </ul>
        <h3>Bottoms</h3>
        <ul>
          <li>Sizes: <%= BottomSize.all.sample.name %></li>
          <li>Budget: max $150</li>
          <li>Fit: <%= BottomFit.all.sample.name %></li>
        </ul>
        <h3>Dresses</h3>
        <ul>
          <li>Sizes: <%= DressSize.all.sample.name %></li>
          <li>Budget: max $150</li>
        </ul>
        <h3>Build considerations: <%= BodyBuild.all.sample(2).map(&:name).join(', ') %></h3>
        <% rand_shape = BodyShape.all.sample%>
        <h3>Body shape: <%= rand_shape.name%></h3>
        <h4><%= rand_shape.description %></h4>
        <%= image_tag("body_shapes/#{rand_shape.name.downcase.gsub(' ','-')}.jpg",
                      alt: rand_shape.name, class: 'img-responsive')%>
        <h3>Loved looks: </h3>
        <div class="row">
          <% Look.all.sample(3).each do |look|%>
              <div class="col-xs-4">
                <%= image_tag(look.image_path, alt: look.name, class: 'img-responsive') %>
              </div>
          <% end %>
        </div>
        <h3>Values: <%= SpecialConsideration.all.sample(2).map(&:name).join(', ') %></h3>
        <h3>Parts to flaunt: <%= Part.all.sample(2).map(&:name).join(', ') %></h3>
        <h3>Parts to downplay: <%= Part.all.sample.name %></h3>
        <h3>Colors to avoid: <%= Color.all.sample(2).map(&:name).join(', ') %></h3>
      </div>
    </div>
  </div>
</div>

app/views/drop_ins/_star_rating.html.erb
<% (1..5).each do |idx| %>
  <div class="col-xs-1">
    <i class="fa fa-star fa-lg <%= ' fa-star-selected' if !rating.nil? && idx <= rating %>"></i>  
  </div>
<% end %>

app/views/drop_ins/_upcoming_for_retail_user.html.erb
<div class="content">
  <div class="col-xs-8">
    <h3><%= drop_in.user.first_name %></h3>
    <h3><%= drop_in.colloquial_time %></h3>
    <% if drop_in.canceled? %>
        <div class="row">
          <div class="col-sm-8 col-md-4">
            <h3 class="alert-danger">CANCELED</h3>
          </div>
        </div>
    <% end %>
    <% unless drop_in.comment.blank? %>
        <h4>"<%= drop_in.comment %>"</h4>
    <% end %>
  </div>
  <div class="col-xs-4 text-center">
    <h1>
      <i class="show-preferences-toggle fa fa-caret-right"></i>
    </h1>
  </div>
  <div class="col-xs-8 col-xs-offset-2 preferences-details">
    <%= render 'shared/style_preferences',
               profile: drop_in.user.style_profile %>
  </div>
</div>

app/views/drop_ins/_upcoming_for_shopper.html.erb
<div class="content">
  <div class="col-xs-2 text-center">
    <% unless drop_in.canceled? %>
    <h1>
      <a id="cancel" data-confirm="Are you sure you want to cancel this booking?"
         data-method="patch"
         href=<%= cancel_drop_in_path(drop_in) %>
                 rel="nofollow"><i class="fa fa-times"></i></a>
    </h1>
    <% end %>
  </div>
  <div class="col-xs-10">
    <h3><%= link_to drop_in.retailer.name, retailer_path(drop_in.retailer)%></h3>
    <h4><%= drop_in.colloquial_time %></h4>
    <% if drop_in.canceled? %>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <h4 class="alert-danger">CANCELED</h4>
          </div>
        </div>
    <% end %>
    <h4><%= drop_in.retailer.get_drop_in_location(drop_in.time.to_s).stringify %></h4>
    <h4><%= drop_in.comment %></h4>
  </div>
</div>

app/views/drop_ins/upcoming.html.erb
<% provide(:title, 'My Drop-Ins') %>

<%= render "shared/header" %>

<div class="bookings container">
  <% if shopper_signed_in? && never_had_drop_in?(current_user) %>
      <%= render "shared/experience" %>
  <% elsif retailer_signed_in? && current_user.retailer.drop_ins.empty? %>
      <br />
      <div class="row text-center">
        <h3>No one has booked a styling at your store yet.</h3><br />
        <h3>Here's a sample to prepare you for your first booking. </h3>
      </div>
      <br />
      <%= render 'sample_booking_for_retailer' %>
  <% else %>
      <div class="row text-center">
        <h3>Here are your style session bookings.</h3><br />
      </div>
      <% if shopper_signed_in? %>
          <% @drop_ins.each do |drop_in| %>
              <% if drop_in.time < Time.zone.now && !drop_in.canceled? %>
                  <div id="drop_in_<%= drop_in.id %>" class="row">
                    <div class="single-booking col-xs-10 col-xs-offset-1">
                      <%= render 'previous_for_shopper', drop_in: drop_in %>
                    </div>
                  </div>
              <% elsif drop_in.time > Time.zone.now %>
                  <div id="drop_in_<%= drop_in.id %>" class="row">
                    <div class="single-booking col-xs-10 col-xs-offset-1">
                      <%= render 'upcoming_for_shopper', drop_in: drop_in %>
                    </div>
                  </div>
              <% end %>
          <% end %>
      <% end %>
      <% if retailer_signed_in? %>
          <% @drop_ins.each do |drop_in| %>
              <% if drop_in.time < Time.zone.now && !drop_in.canceled? %>
                  <div id="drop_in_<%= drop_in.id %>" class="row">
                    <div class="single-booking col-xs-10 col-xs-offset-1">
                      <%= render 'previous_for_retail_user', drop_in: drop_in %>
                    </div>
                  </div>
              <% elsif drop_in.time > Time.zone.now %>
                  <div id="drop_in_<%= drop_in.id %>" class="row">
                    <div class="single-booking col-xs-10 col-xs-offset-1">
                      <%= render 'upcoming_for_retail_user', drop_in: drop_in %>
                    </div>
                  </div>
              <% end %>
          <% end %>
      <% end %>
  <% end %>
</div>