config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'

  get '/about'            =>  'static_pages#about'
  get '/retailer_info'    =>  'static_pages#retailer_info'
  get '/experience'       =>  'static_pages#experience'
  get '/decal'            =>  'static_pages#decal'
  get '/relaunch'         =>  'static_pages#relaunch'
  get '/join_confirmation'=>  'static_pages#join_confirmation'
  get '/confirmation_required'  => 'static_pages#confirmation_required'

  post 'swipe_styles/invite'    => 'swipe_styles#invite'
  get 'swipe_styles/new'        => 'swipe_styles#new'
  get 'swipe_styles/results'    => 'swipe_styles#results'
  post 'swipe_styles/like'      => 'swipe_styles#like'
  post 'swipe_styles/complete'  => 'swipe_styles#complete'
  delete 'swipe_styles/destroy' => 'swipe_styles#destroy'
  post 'swipe_styles/update_matches' => 'swipe_styles#update_matches'
  post 'swipe_styles/update_style_needs' => 'swipe_styles#update_style_needs'

  resources :share_quizzes, param: :name, only: [:show]

  namespace :webhooks do
    get 'mailchimp/subscribe'  => 'mailchimp_importer#validate'
    post 'mailchimp/subscribe' => 'mailchimp_importer#subscribe'
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  scope module: 'users' do
    resources :users, only: [] do
      collection do
        get :shoppers
      end
    end
  end

  resources :style_profiles, only: [:edit, :update, :new, :create] do
    collection do
      post :quickstart
    end
  end

  resources :retailers, only: [:show, :index, :new, :create] do
    member do
      get 'scheduled_availabilities'
      get 'enable_available_dates'
      get 'enable_available_times'
      get 'show_drop_in_location'
      get 'press_kit'
    end
  end

  resources :drop_ins, only: [:create, :update, :destroy] do
    member do
      patch :cancel
    end
    collection do
      get :upcoming
    end
  end

  resources :drop_in_availabilities, only: [:create, :update] do
    collection do
      get :personal
    end
  end

  get 'drop_in_availabilities/apply_form' => 'drop_in_availabilities#apply_form'

  resources :reports, only: [:new, :create]

  resources :retailer_referrals, only: [:create]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :go_to_relaunch, :only => [:about, :experience]
  skip_filter :authenticate_shopper!
  
  def home
  end

  def about
  end

  def retailer_info
  end

  def blog
  end

  def experience
  end

  def relaunch
  end

  def join_confirmation
  end

  def decal
    response.headers.delete('X-Frame-Options')
    @retailer = Retailer.find(params[:retailer_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_how_it_works.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <div class="service-item text-center">
      <a href=<%= experience_path %>>
        <%= image_tag("survey.jpg", class: "img-responsive center-block") %>
      </a>
      <h3>Create a personalized style profile to capture your unique style preferences.</h3>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="service-item text-center">
      <a href=<%= experience_path %>>
        <%= image_tag("boutique.jpg", class: "img-responsive center-block") %>
      </a>
      <h3>Discover neighborhood fashion boutiques and learn about their story, values, and owners.</h3>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="service-item text-center">
      <a href=<%= experience_path %>>
        <%= image_tag("dress.jpg", class: "img-responsive center-block") %>
      </a>
      <h3>Book FREE styling sessions. Walk in to find hand-picked items for your shape, size, budget, and more.</h3>
    </div>
  </div>
</div>

app/views/static_pages/_index_non_authenticated.html.erb
<% content_for :page_header do %>
    <%= stylesheet_link_tag 'homepage' %>
    <%= javascript_include_tag 'homepage' %>
<% end %>

<% retailer = Retailer.all_live.sample unless Retailer.all_live.empty? %>

<%= render "shared/header" %>

<header id="myCarousel" class="carousel slide">
  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <% Retailer.showcase.each_with_index do |retailer, idx| %>
        <div class="item <%= 'active' if idx == 0%>">
          <div class="fill" style="background-image:url('<%= retailer.above_fold_image %>');"></div>
          <div class="carousel-caption">
            <h3>Featured boutique: <%= retailer.name %></h3>
            <h4><%= retailer.location.neighborhood %></h4>
          </div>
        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>
<div class="above-fold-banner">
  <div class="contents">
    <div class="large-screen">
      <div class="col-xs-7 logo vcenter">
        <%= image_tag("logo_white.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-xs-3 col-md-3 tag-line text-center vcenter">
        <div class="banner-text">
          <h3>No need to shop with the masses.</h3>
          <h3>Find your perfect boutique and outshine the rest.</h3>
        </div>
        <div class="cta-buttons col-xs-12">
          <div class="col-xs-6 text-center">
            <a class="move-learn-more btn btn-default btn-lg pull-right">Learn More</a>
          </div>
          <div class="col-xs-6 text-center">
            <a class="move-join-now btn btn-default btn-lg pull-left">Join Beta</a>
          </div>
        </div>
      </div>
    </div>
    <div class="small-screen landscape">
      <div class="col-xs-7 logo vcenter">
        <%= image_tag("logo_white.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-xs-4 tag-line text-center vcenter">
        <div class="banner-text">
          <h3>No need to shop with the masses.</h3>
          <h3>Find your perfect boutique and outshine the rest.</h3>
        </div>
        <div class="cta-buttons col-xs-12">
          <div class="col-xs-6 text-center">
            <a class="move-learn-more btn btn-default btn-lg pull-right">Learn More</a>
          </div>
          <div class="col-xs-6 text-center">
            <a class="move-join-now btn btn-default btn-lg pull-left">Join Beta</a>
          </div>
        </div>
      </div>
    </div>
    <div class="small-screen portrait">
      <div class="col-xs-12 logo vcenter">
        <%= image_tag("logo_white.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-xs-12 tag-line text-center vcenter">
        <div class="banner-text">
          <h3>No need to shop with the masses.</h3>
          <h3>Find your perfect boutique and outshine the rest.</h3>
        </div>
        <div class="cta-buttons col-xs-12">
          <div class="col-xs-6 text-center">
            <a class="move-learn-more btn btn-default btn-lg pull-right">Learn More</a>
          </div>
          <div class="col-xs-6 text-center">
            <a class="move-join-now btn btn-default btn-lg pull-left">Join Beta</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="homepage">
  <div class="more-about-us" id="more-about-us">
    <div class="layer">
      <div class="container">
        <div class="content">
          <div class="row">
            <div class="main-text col-xs-12 col-sm-6 text-center">
              <h4 class="large-screen">
                Focused on style not fads, OpenStile will match you with Brooklyn boutiques to enhance your personal style.
                Get undivided attention from the boutique who will work with you to find the perfect pieces for your wardrobe.
                Our services are always complimentary with no obligation to buy. Enjoy shopping again and be the ultimate you.
              </h4><br />
              <h4 class="small-screen">
                Focused on style not fads, OpenStile will match you with Brooklyn boutiques to enhance your personal style.
                Our boutiques work with you to find the perfect pieces for your wardrobe.
              </h4><br />
              <ul class="small-screen">
                <li>Services always complimentary.</li>
                <li>Never any obligation to buy.</li>
                <li>Enjoy shopping again.</li>
                <li>Be the ultimate you.</li>
              </ul>
              <%= link_to 'more about us', about_path, class: 'btn btn-default' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="benefits text-center">
    <span class="large-screen"><h2>Benefits of OpenStile</h2></span>
    <div class="highlights container">
      <div class="row">
        <div class="col-xs-4">
          <i class="fa fa-heart-o fa-4x" aria-hidden="true"></i>
          <h4>Love Shopping Again</h4>
          <p class="large-screen text">
            No more crowded stores or waiting in lines.
            Enjoy personal attention as well as fashion designed for unique individuals like yourself, and not for&nbsp;the&nbsp;masses.
          </p>
        </div>
        <div class="col-xs-4">
          <i class="fa fa-clock-o fa-4x" aria-hidden="true"></i>
          <h4>Save Time and Money</h4>
          <p class="large-screen text">
            No more rummaging through racks or be stuck in dressing rooms.  Our services are complimentary and our in-house
            boutique stylists will curate everything for you based off your style, budget, and needs before&nbsp;you&nbsp;arrive.
          </p>
        </div>
        <div class="col-xs-4">
          <i class="fa fa-diamond fa-4x" aria-hidden="true"></i>
          <h4>Discover Unique Pieces</h4>
          <p class="large-screen text">
            Never get caught wearing the same thing as anyone else again.
            Love the pieces you find not just for their exclusive designs, but the designers&nbsp;behind&nbsp;them.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="image-break small-screen"></div>
  <div class="how-it-works small-screen">
    <div class="banner row text-center">
      <h1>It's Easy!</h1>
    </div>
    <div class="row">
      <div class="step col-xs-12">
        <div class="number col-xs-2 col-xs-offset-1 vcenter">
          <span class="fa-stack fa-5x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">1</strong>
          </span>
        </div>
        <div class="text-left col-xs-7 col-xs-offset-1 vcenter">
          <h2>Create a Style Profile</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="step col-xs-12">
        <div class="number col-xs-2 col-xs-offset-1 vcenter">
          <span class="fa-stack fa-5x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">2</strong>
          </span>
        </div>
        <div class="text-left col-xs-7 col-xs-offset-1 vcenter">
          <h2>Set free appointment at your top matched&nbsp;boutiques</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="step col-xs-12">
        <div class="number col-xs-2 col-xs-offset-1 vcenter">
          <span class="fa-stack fa-5x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">3</strong>
          </span>
        </div>
        <div class="text-left col-xs-7 col-xs-offset-1 vcenter">
          <h2>Arrive at your appointment. Enjoy shopping fashion that truly expresses the ultimate&nbsp;you</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="how-it-works large-screen">
    <div class="row">
      <div class="banner col-xs-8 col-xs-offset-4 col-md-5 col-md-offset-7">
        <h1>It's Easy!</h1>
      </div>
    </div>
    <div class="row">
      <div class="step col-md-5 col-md-offset-7 col-lg-4 col-lg-offset-7">
        <div class="number col-xs-2 vcenter">
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">1</strong>
          </span>
        </div>
        <div class="text-center col-xs-9 vcenter">
          <h4>Create a Style Profile</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="step col-md-5 col-md-offset-7 col-lg-4 col-lg-offset-7">
        <div class="number col-xs-2 vcenter">
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">2</strong>
          </span>
        </div>
        <div class="text-center col-xs-9 vcenter">
          <h4>Set free appointment at your top matched boutiques</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="step col-md-5 col-md-offset-7 col-lg-4 col-lg-offset-7">
        <div class="number col-xs-2 vcenter">
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <strong class="fa-stack-1x">3</strong>
          </span>
        </div>
        <div class="text-center col-xs-9 vcenter">
          <h4>Arrive at your appointment. Enjoy shopping fashion that truly expresses the ultimate you</h4>
        </div>
      </div>
    </div>
    <div class="row action-link">
      <div class="col-xs-6 col-xs-offset-4 col-md-4 col-md-offset-7 text-center">
        <%= link_to 'how it works', experience_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class="signup" id="join-now">
    <div class="layer">
      <div class="container">
        <div class="row">
          <div class="form-block col-lg-5 col-lg-offset-0 col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
            <div class="text-center">
              <h3>Sign Up with OpenStile Today</h3><br/>
            </div>
            <%= react_component 'ShopperInterest', data: {}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    $('.move-learn-more').click(function() {
        $('#more-about-us').get(0).scrollIntoView();
        return false;
    });
    $('.move-join-now').click(function() {
        $('#join-now').get(0).scrollIntoView();
        return false;
    });
    $(document).ready(function (){
        $('.carousel').carousel({
            interval: 5000
        });
    });
</script>

<% set_meta_tags og: {
                         locale: 'en_US',
                         type:     'website',
                         title:    'OpenStile | Hand-picked style at your favorite local boutiques',
                         description: 'OpenStile lets you book FREE personal styling sessions at neighborhood boutiques.' +
                                      ' Walk in to find items pre-selected based on your likes, budget, body type and more!',
                         url:      'http://www.openstile.com',
                         image:    'https://res.cloudinary.com/openstile/image/upload/v1447729511/openstilelogo-small-square_rx8yto.png'
                 }
%>

<% set_meta_tags twitter: {
                         card: "summary_large_image",
                         site: "@OpenStile"
                 }
%>

app/views/static_pages/_mailer_header.html.erb
<header>
  <div class="container">
    <div class="row intro-message">
      <p><%= intro_message %></p>
    </div>
    <div class="row text-center">
      <div class="col-xs-6 col-xs-offset-3 logo">
        <a id='logo-home' href=<%= root_path %>>
          <%= image_tag('openstilelogo.png', class: 'img-responsive center-block', width: '400') %>
        </a>
      </div>
      <div class="col-xs-12 navigation">
        <%= link_to "Boutiques", retailers_path, class: 'col-sm-6 btn-default ' %>
        <%= link_to "Blog", blog_articles_path, class: 'col-sm-6 btn-default' %>
      </div>
    </div>
  </div>
</header>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<% content_for :page_header do %>
    <%= stylesheet_link_tag 'about' %>
<% end %>

<%= render 'shared/header' %>

<div class="about-us">
  <div class="above-the-fold">
    <div class="layer">
      <div class="row text">
        <div class="why-us col-xs-6 col-md-4 col-md-offset-1">
          <span class="large-screen">Going through endless racks, finding the right size, and a workout in the dressing room;
          shopping used to be a luxury and we should bring that back.
          We found that boutiques do a better job in giving great service and focusing on individual style instead of trending fads.
          They don't need to break your wallet either.   <br /><br /></span>
          Support real clothing by real designers who fill their work with heart.
          You are not sheep in a herd, but an amazing individual. So why settle for fashion produced in the millions? Express the ultimate you.
          <ul class="small-screen">
            <li>Services always complimentary.</li>
            <li>Never any obligation to buy.</li>
            <li>Enjoy shopping again.</li>
            <li>Be the ultimate you.</li>
          </ul>
          <div class="action small-screen">
            <a href="/#join-now" class="btn btn-default btn-lg">Join Beta</a>
          </div>
        </div>
        <div class="large-screen col-xs-3 col-xs-offset-3">
          <div class="cta text-right">
            Complimentary Services. Never any obligation to buy. Just enjoy being the ultimate you.
          </div>
          <div class="action col-xs-6 col-xs-offset-6">
            <a href="/#join-now" class="btn btn-default btn-lg pull-right">Join Beta</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="founders-banner text-center">
    <h1>Meet Our Founders</h1>
  </div>
  <div class="large-screen">
    <div class="profile-pics">
      <div class="row">
        <div class="col-xs-6">
          <div class="col-xs-8 col-xs-offset-2">
            <%= cl_image_tag("sparkle_johnson_founder.jpg", :gravity=>"face", :height=>400, :width=>400, :crop=>"fill", :class=>"img-responsive center-block") %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="col-xs-8 col-xs-offset-2">
            <%= cl_image_tag("tamara_austin_founder.jpg", :gravity=>"face", :height=>400, :width=>400, :crop=>"fill", :class=>"img-responsive center-block") %>
          </div>
        </div>
      </div>
    </div>
    <div class="bios">
      <div class="row">
        <div class="col-xs-6 text-center">
          <h2>Sparkle Johnson</h2>
          <h4>"In order to be irreplaceable one must always be different."<br /> Coco Chanel</h4>
          <div class="col-xs-12">
            <h3>
              Sparkle, a lifelong native of Brooklyn, knew the value of launching the OpenStile service in such a diverse landscape with so
              many different boutiques that cater to different styles. She brings to OpenStile her passion for fashion along
              with a broad range of experience in different fields of work such as healthcare technology and graphic design.
            </h3>
          </div>
        </div>
        <div class="col-xs-6 text-center">
          <h2>Tamara Austin</h2>
          <h4>"Style is knowing who you are, what you want to say, and not giving a damn."<br /> Gore Vidal</h4>
          <div class="col-xs-12">
            <h3>
              Tamara comes from a background in tech. After graduating from the University of Virginia with a degree in Computer Science,
              she worked as a software engineer and IT consultant in the Washington DC area. She started OpenStile as a way to directly
              apply her technical expertise to her entrepreneurial passions.
            </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="small-screen profiles">
    <div class="row">
      <div class="col-xs-4 profile-pics vcenter">
        <%= cl_image_tag("sparkle_johnson_founder.jpg", :gravity=>"face", :height=>250, :width=>250, :crop=>"fill", :class=>"img-responsive center-block") %>
      </div>
      <div class="col-xs-7 bios text-center vcenter">
        <h2>Sparkle Johnson</h2>
        <h4>"In order to be irreplaceable one must always be different."<br /> Coco Chanel</h4>
        <h3>
            Sparkle, a lifelong native of Brooklyn, knew the value of launching the OpenStile service in such a diverse landscape with so
            many different boutiques that cater to different styles. She brings to OpenStile her passion for fashion along
            with a broad range of experience in different fields of work such as healthcare technology and graphic design.
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-7 bios text-center vcenter">
        <h2>Tamara Austin</h2>
        <h4>"Style is knowing who you are, what you want to say, and not giving a damn."<br /> Gore Vidal</h4>
        <h3>
            Tamara comes from a background in tech. After graduating from the University of Virginia with a degree in Computer Science,
            she worked as a software engineer and IT consultant in the Washington DC area. She started OpenStile as a way to directly
            apply her technical expertise to her entrepreneurial passions.
        </h3>
      </div>
      <div class="col-xs-4 profile-pics vcenter">
        <%= cl_image_tag("tamara_austin_founder.jpg", :gravity=>"face", :height=>250, :width=>250, :crop=>"fill", :class=>"img-responsive center-block") %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>

<div class="block">
  <div class="container">
    <div class="page-title text-center">
      <h3>OpenStile Blog</h3>
    </div>
    <hr>

    <div class="blog-thumbnails">
      <div class="row">
        <div class="col-md-6 portfolio-item">
          <%= render "blog_01" %>
        </div>
        <!-- Placeholder for next blog -->
        <!--div class="col-md-6 portfolio-item">
          < %= render "blog_01" %>
        </div-->
      </div>
    </div>
  </div>
</div>

<%= render "shared/google_analytics" %>

app/views/static_pages/confirmation_required.html.erb
<% provide(:title, 'Confirm Email') %>

<%= render "shared/header" %>

<div class="join_now">
  <div class="container">
    <div class="row">
      <div class="thanks col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
        <div class="contents text-center">
          <h2>Thanks for Signing Up!</h2>
          <h3>We need you to confirm your email address.</h3>
          <div class="icon">
            <%= image_tag('signup_success.png', width: 100, class: 'img-responsive center-block') %>
          </div>
          <h3>Please click the link in the email we just sent you.</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/decal.html.erb
<% provide(:embeddable, true) %>
<a href=<%= retailer_path(@retailer) %> target='_blank'>
  <%= image_tag "retailer_widget.jpg", class: "img-responsive" %>
</a>

app/views/static_pages/experience.html.erb
<% provide(:title, 'How it Works') %>

<% content_for :page_header do %>
    <%= stylesheet_link_tag 'how_it_works' %>
<% end %>

<%= render 'shared/header' %>

<div class="experience">
  <div class="how-it-works">
    <div class="row">
      <div class="body col-xs-9 col-xs-offset-3 col-lg-5 col-lg-offset-4">
        <div class="step col-xs-12">
          <div class="number col-xs-2 vcenter">
            <span class="fa-stack fa-3x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <strong class="fa-stack-1x">1</strong>
            </span>
          </div>
          <div class="col-xs-8 col-xs-offset-1 text-center vcenter">
            <h3>Create a Style Profile</h3>
            <h4>
              After you sign up, we will send you a questionnaire to give us a sense of your style as well as sizing preferences.
            </h4>
          </div>
        </div>
        <div class="step col-xs-12">
          <div class="number col-xs-2 vcenter">
            <span class="fa-stack fa-3x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <strong class="fa-stack-1x">2</strong>
            </span>
          </div>
          <div class="col-xs-8 col-xs-offset-1 text-center vcenter">
            <h3>Set a boutique appointment</h3>
            <h4>
              Tell us the date and times you are available, your upcoming events, and your ideal budget,
              and we will match you with the best boutique based off of your criteria.
            </h4>
          </div>
        </div>
        <div class="step col-xs-12">
          <div class="number col-xs-2 vcenter">
            <span class="fa-stack fa-3x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <strong class="fa-stack-1x">3</strong>
            </span>
          </div>
          <div class="col-xs-8 col-xs-offset-1 text-center vcenter">
            <h3>Arrive at your appointment</h3>
            <h4>
              Everything is curated and prepared before your arrival.
              Work with the boutique to get your perfect look and learn
              about the store, designers, neighborhood, and more.
            </h4>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-lg-3 cta">
        <div class="text text-right">
          Complimentary Services. <br /> Never any obligation to buy. <br />
          Just enjoy being the ultimate you.
        </div>
        <div class="action col-xs-6 col-xs-offset-6">
          <a href="/#join-now" class="btn btn-default pull-right">Join Beta</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Hand-picked items at your favorite local boutiques') %>

<% if admin_signed_in? %>
    <%= render partial: 'shared/signed_in_admin' %>
<% elsif retailer_signed_in? %>
    <%= render partial: 'shared/signed_in_retail_user' %>
<% else %>
    <%= render partial: 'index_non_authenticated' %>
<% end %>

app/views/static_pages/join_confirmation.html.erb
<% provide(:title, 'Welcome') %>

<% content_for :page_header do %>
    <%= stylesheet_link_tag 'join_now' %>
<% end %>

<%= render "shared/header" %>

<div class="join_now">
  <div class="container">
    <div class="row">
      <div class="thanks col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
        <div class="contents text-center">
          <h2>Thanks for Signing Up!</h2>
          <h3>We are excited to start styling with you! We will be in touch about your access to our beta.</h3>
          <div class="icon">
            <%= image_tag('signup_success.png', width: 100, class: 'img-responsive center-block') %>
          </div>
          <h3>In the meantime, check out our</h3>
          <a class="btn btn-default" href="http://blog.openstile.com">Style Blog</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/relaunch.html.erb
<% provide(:title, 'Relaunch') %>

<%= render "shared/header" %>

<div class="signup container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 login-section">
      <br /><br />
      <h4 class="text-center">Thanks for your patience as we make updates to our site and service.</h4>
      <br />
      <h4 class="text-center">Expect great things once the dust settles, and stay tuned for our relaunch!</h4>
      <br /><br />
    </div>
  </div>
</div>