config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'

  get '/about'            =>  'static_pages#about'
  get '/retailer_info'    =>  'static_pages#retailer_info'
  get '/experience'       =>  'static_pages#experience'
  get '/decal'            =>  'static_pages#decal'
  get '/relaunch'         =>  'static_pages#relaunch'
  get '/join_confirmation'=>  'static_pages#join_confirmation'
  get '/confirmation_required'  => 'static_pages#confirmation_required'

  post 'swipe_styles/invite'    => 'swipe_styles#invite'
  get 'swipe_styles/new'        => 'swipe_styles#new'
  get 'swipe_styles/results'    => 'swipe_styles#results'
  post 'swipe_styles/like'      => 'swipe_styles#like'
  post 'swipe_styles/complete'  => 'swipe_styles#complete'
  delete 'swipe_styles/destroy' => 'swipe_styles#destroy'
  post 'swipe_styles/update_matches' => 'swipe_styles#update_matches'
  post 'swipe_styles/update_style_needs' => 'swipe_styles#update_style_needs'

  resources :share_quizzes, param: :name, only: [:show]

  namespace :webhooks do
    get 'mailchimp/subscribe'  => 'mailchimp_importer#validate'
    post 'mailchimp/subscribe' => 'mailchimp_importer#subscribe'
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  scope module: 'users' do
    resources :users, only: [] do
      collection do
        get :shoppers
      end
    end
  end

  resources :style_profiles, only: [:edit, :update, :new, :create] do
    collection do
      post :quickstart
    end
  end

  resources :retailers, only: [:show, :index, :new, :create] do
    member do
      get 'scheduled_availabilities'
      get 'enable_available_dates'
      get 'enable_available_times'
      get 'show_drop_in_location'
      get 'press_kit'
    end
  end

  resources :drop_ins, only: [:create, :update, :destroy] do
    member do
      patch :cancel
    end
    collection do
      get :upcoming
    end
  end

  resources :drop_in_availabilities, only: [:create, :update] do
    collection do
      get :personal
    end
  end

  get 'drop_in_availabilities/apply_form' => 'drop_in_availabilities#apply_form'

  resources :reports, only: [:new, :create]

  resources :retailer_referrals, only: [:create]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p>Oops, there was an error saving the information</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_experience.html.erb
<div class="experience container">
  <div class="content row">
    <div class="col-xs-12 text-center">
      <h4>SHOP LIKE A VIP</h4><br />
    </div>
    <div class="col-xs-12">
      <%= image_tag("garment_bag.jpg", class: "img-responsive center-block") %>
    </div>
    <div class="col-xs-12 text-center">
      <br /><h5>When you shop with OpenStile, our stores will know:</h5>
      <ul>
        <li>When you're coming in</li>
        <li>What you do and don't like</li>
        <li>What you're actively seeking</li>
      </ul>
      <h5>
        Powered by this knowledge they'll pre-select a few
        outfits for your personalized OpenStile Garment bag!
      </h5><br />
      <% unless Retailer.all_live.empty? %>
          <% sample_retailer = Retailer.all_live.sample %>
          <div class="text-center">
            <%= link_to("Treat yourself to a FREE styling at #{sample_retailer.name}!",
                        retailer_path(sample_retailer), class: "btn btn-lg btn-default try-today opn-btn")%>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_forgot_password.html.erb
<% provide(:title, 'Forgot Password') %>

<%= render "shared/header" %>

<div class="signup container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 login-section">
      <div class="text-center">
        <h4>Reset your password</h4>
        <br/>
      </div>
      <%= form_for(resource, as: resource_name,
                   url: password_path(resource_name),
                   html: {method: :post}) do |f| %>

          <%= devise_error_messages! %>

          <div class="field form-group">
            <%= f.label :email, class: "col-md-12" %><br />
            <%= f.email_field :email, class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit "Send me reset password instructions",
                         class: "col-md-6 col-xs-8 btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56170951-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-openstile">
  <div class="container-fluid">
    <div class="navbar-header">
      <% unless current_page?(controller: '/static_pages', action: 'home') %>
        <a class="navbar-brand large-screen" id="header-brand" href="/"><%= image_tag('logo_white.png', class: 'img-responsive center-block', width: 300) %></a>
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'home', root_path, class: 'small-screen' %></li>
        <li><%= link_to 'how it works', experience_path %></li>
        <li><%= link_to 'about us', about_path %></li>
        <li><a href="http://blog.openstile.com">style blog</a></li>
        <!-- li><a href="#">contact us</a></li -->
        <li><a href="/#join-now" class="small-screen">sign up</a></li>
        <li><a class="btn btn-default large-screen" href="/#join-now">sign up</a></li>
        <% if shopper_signed_in? %>
            <li><%= link_to 'Style Profile', edit_style_profile_path(current_user.style_profile) %></li>
        <% end %>
        <% if retailer_signed_in? %>
            <li><%= link_to 'Update account', edit_user_password_path(current_user) %></li>
        <% end %>
        <% if user_signed_in? %>
            <li><%= link_to 'Boutiques', retailers_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_reset_password.html.erb
<% provide(:title, 'Password Reset') %>

<%= render "shared/header" %>

<div class="signup container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 login-section">
      <div class="text-center">
        <h4>Reset your password</h4>
        <br/>
      </div>
      <%= form_for(resource, as: resource_name,
                   url: password_path(resource_name),
                   html: {method: :put}) do |f| %>

          <%= devise_error_messages! %>
          <%= f.hidden_field :reset_password_token %>

          <div class="field form-group">
            <%= f.label :password, "New password" %>
            <% if @validatable %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="field form-group">
            <%= f.label :password_confirmation, "Confirm new password" %>
            <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit "Reset my password",
                         class: "col-md-6 col-xs-8 btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_schedule_drop_in.html.erb
<div data-retailer-id=<%= retailer.id %> class="drop-in" id="drop-in">
  <div class="row text-center">
    <h3>
      When you book a FREE styling <%= retailer.user.first_name %> and the <%= retailer.name %> team will
      have hand-picked items ready and waiting for you.
    </h3>
  </div>

  <% if shopper_signed_in? %>
  <div class="row text-center text-danger">
    <br />
    <% incompatibilities = shopper_store_incompatibilities(current_user, retailer) %>
    <h3><%= "***Just a head's up #{current_user.first_name.capitalize}! #{incompatibilities.join('. ')}***" unless incompatibilities.empty? %></h3>
  </div>
  <% end %>

  <div class="row schedule">
    <% asap_time = Time.zone.now.advance(minutes: 30) %>
    <% new_drop_in = @drop_in || retailer.drop_ins.build(user_id: user_signed_in? ? current_user.id : nil) %>
    <div class="col-xs-6 asap <%= 'dn' unless retailer.available_for_drop_in? asap_time %>">
      <div class="col-xs-8 col-md-6 col-md-offset-2">
        <%= form_for(new_drop_in) do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.hidden_field :retailer_id %>

            <input id="drop_in[selected_date]" name="drop_in[selected_date]"
                   type="hidden" value="<%= asap_time.strftime('%F') %>">

            <input id="drop_in[selected_time]" name="drop_in[selected_time]"
                   type="hidden" value="<%= ActiveSupport::TimeZone[Time.zone.name].parse(asap_time.to_s).strftime('%H:%M') %>">

            <%= f.submit ("I'll be there in 30 minutes!"),
                         class: "btn btn-lg btn-default opn-btn #{'disabled' if retailer_signed_in?}" %>
            <span class="help-block"><%= 'Sorry, store owners cannot book sessions' if retailer_signed_in? %></span>
        <% end %>
      </div>
      <div class="col-xs-4 text-center">
        <h3>- or -</h3>
      </div>
    </div>
    <div class="col-xs-6 <%= 'col-xs-offset-3' unless retailer.available_for_drop_in? asap_time %> full">
      <%= form_for(new_drop_in) do |f| %>
          <div class="text-center">
            <%= render 'shared/error_messages', object: f.object %>
          </div>

          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :retailer_id %>

          <div class="row form-group">
            <label class="sr-only" for="drop_in[selected_date]">Date</label>
              <input id="drop_in[selected_date]" name="drop_in[selected_date]"
                     class="form-control input-lg opn-btn datepicker" placeholder="Pick a Date"
                     value="<%= new_drop_in.time.strftime('%F') unless new_drop_in.time.blank? %>">
          </div>

          <div class="row form-group">
            <label class="sr-only" for="drop_in[selected_time]">Time</label>
              <input id="drop_in[selected_time]" name="drop_in[selected_time]"
                     class="form-control input-lg opn-btn timepicker" placeholder="Pick a Time">
          </div>

          <div class="row form-group">
            <%= f.label :comment, class: "sr-only"%>
            <%= f.text_area :comment, class: "form-control input-lg opn-btn",
                            placeholder: "Additional info (i.e Need a new work wardrobe)",
                            size: "24x6"%>
          </div>

          <div class="row form-group">
            <%= f.submit (user_signed_in? ? 'Book session' : 'Sign in and Book session'),
                         class: "btn btn-lg btn-default opn-btn #{'disabled' if retailer_signed_in?}" %>
            <span class="help-block"><%= 'Sorry, store owners cannot book sessions' if retailer_signed_in? %></span>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_signed_in_admin.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="row text-center">
    <h2>Admin Home</h2>
  </div>
  <div class="row">
    <h3><%= link_to 'Manage retailers', retailers_path %></h3>
  </div>
  <div class="row">
    <h3><%= link_to 'Generate report', new_report_path %></h3>
  </div>
  <div class="row">
    <h3><%= link_to 'View all shoppers', shoppers_users_path %></h3>
  </div>
</div>

app/views/shared/_signed_in_retail_user.html.erb
<%= render "shared/header" %>

<div class="dashboard container">
  <div class="row tiles">
    <div class="col-xs-12 col-md-6">
      <div class="tile tile-1 text-center">
        <a href="<%= retailer_path current_user.retailer %>">
          <h3>View my store page</h3><br />
          <h3><i class="fa fa-2x fa-building-o"></i></h3><br />
          <h4>This is a preview of what shoppers will see when they visit your store's page.</h4>
        </a>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="tile tile-2 text-center">
        <a href="<%= upcoming_drop_ins_path %>">
          <h3>View my bookings</h3><br />
          <h3><i class="fa fa-2x fa-users"></i></h3><br />
          <h4>See who’s coming in and what they’re looking for. Also rate past bookings so we can keep improving the service.</h4>
        </a>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="tile tile-3 text-center">
        <a href="<%= personal_drop_in_availabilities_path %>">
          <h3>Manage my availability</h3><br />
          <h3><i class="fa fa-2x fa-calendar"></i></h3><br />
          <h4>Control when shoppers can book style sessions by setting your availability.</h4>
        </a>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="tile tile-4 text-center">
        <a href="<%= press_kit_retailer_path current_user.retailer %>">
          <h3>Press kit</h3><br />
          <h3><i class="fa fa-2x fa-share-square-o"></i></h3><br />
          <h4>All the pics, posts, tweets and more you need to let the world know you’re on OpenStile.</h4>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_social_media_icons.html.erb
<div class="col-xs-3">
  <a href="https://facebook.com/openstile">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
        </span>
  </a>
</div>
<div class="col-xs-3">
  <a href="https://instagram.com/openstile">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
        </span>
  </a>
</div>
<div class="col-xs-3">
  <a href="https://twitter.com/openstile">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
        </span>
  </a>
</div>
<div class="col-xs-3">
  <a href="https://pinterest.com/openstile">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-pinterest fa-stack-1x fa-inverse"></i>
        </span>
  </a>
</div>

app/views/shared/_start_using_today_button.html.erb
<div class="row text-center">
  <%= link_to "Start using OpenStile today!", 
                           new_shopper_registration_path, 
                           class: "get-started btn-default btn-lg" %>
</div>

app/views/shared/_style_preferences.html.erb
<% unless profile.empty? %>
    <h3>Tops</h3>
    <ul>
      <% unless profile.top_sizes.empty? %>
          <li>Sizes: <%= profile.top_sizes.map(&:name).join(', ') %></li>
      <% end %>
      <% unless profile.top_budget_index.blank? %>
          <li>Budget: <%= StyleProfile::BUDGET_INDEX_MAPPING.key(profile.top_budget_index) %></li>
      <% end %>
      <% unless profile.top_fit.blank? %>
          <li>Fit: <%= profile.top_fit.name %></li>
      <% end %>
    </ul>
    <h3>Bottoms</h3>
    <ul>
      <% unless profile.bottom_sizes.empty? %>
          <li>Sizes: <%= profile.bottom_sizes.map(&:name).join(', ') %></li>
      <% end %>
      <% unless profile.bottom_budget_index.blank? %>
          <li>Budget: <%= StyleProfile::BUDGET_INDEX_MAPPING.key(profile.bottom_budget_index) %></li>
      <% end %>
      <% unless profile.bottom_fit.blank? %>
          <li>Fit: <%= profile.bottom_fit.name %></li>
      <% end %>
    </ul>
    <h3>Dresses</h3>
    <ul>
      <% unless profile.dress_sizes.empty? %>
          <li>Sizes: <%= profile.dress_sizes.map(&:name).join(', ') %></li>
      <% end %>
      <% unless profile.dress_budget_index.blank? %>
          <li>Budget: <%= StyleProfile::BUDGET_INDEX_MAPPING.key(profile.dress_budget_index) %></li>
      <% end %>
    </ul>
    <% unless profile.body_builds.empty? %>
        <h3>Build considerations: <%= profile.body_builds.map(&:name).join(', ') %></h3>
    <% end %>
    <% unless profile.body_shape.nil? %>
        <h3>Body shape: <%= profile.body_shape.name%></h3>
        <h4><%= profile.body_shape.description %></h4>
        <%= image_tag("body_shapes/#{profile.body_shape.name.downcase.gsub(' ','-')}.jpg",
                      alt: profile.body_shape.name, class: 'img-responsive')%>
    <% end %>
    <% unless profile.looks.empty? %>
        <h3>Loved looks: </h3>
        <div class="row">
          <% profile.looks.each do |look|%>
              <div class="col-xs-4">
                <%= image_tag(look.image_path, alt: look.name, class: 'img-responsive') %>
              </div>
          <% end %>
        </div>
    <% end %>
    <% unless profile.special_considerations.empty? %>
        <h3>Values: <%= profile.special_considerations.map(&:name).join(', ') %></h3>
    <% end %>
    <% unless profile.flaunted_parts.empty? %>
        <h3>Parts to flaunt: <%= profile.flaunted_parts.map(&:name).join(', ') %></h3>
    <% end %>
    <% unless profile.downplayed_parts.empty? %>
        <h3>Parts to downplay: <%= profile.downplayed_parts.map(&:name).join(', ') %></h3>
    <% end %>
    <% unless profile.avoided_colors.empty? %>
        <h3>Colors to avoid: <%= profile.avoided_colors.map(&:name).join(', ') %></h3>
    <% end %>
<% else %>
    <h3>No preferences specified</h3>
<% end %>

app/views/shared/_style_profile_quickstart.html.erb
<div class="style-profile">
  <% new_style_profile = StyleProfile.new %>
  <%= form_for(new_style_profile, url: quickstart_style_profiles_path, as: :post) do |f| %>
    <div class="fieldset-group">
      <%= render 'style_profiles/quickstart_fieldsets', style_profile: new_style_profile %>
    </div>
    <input type="submit" name="submit" class="btn btn-lg opn-btn try-today" value="Let's get started!" />
  <% end %>
</div>

app/views/shared/_user_log_in.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3 login-section">
    <div class="text-center">
      <% if type == 'shopper' %>
          <h4><%= link_to "Switch to retailer log in",
                          new_retail_user_session_path %></h4>
          <br/>
      <% elsif type == 'retail_user' %>
          <h4><%= link_to "Switch to shopper log in",
                          new_shopper_session_path %></h4>
          <br/>
    <% end %>
    </div>
    <%= form_for(resource, as: resource_name, 
                           url: session_path(resource_name)) do |f| %>
      <div class="field form-group">
        <%= f.label :email, class: "col-md-12" %><br />
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="field form-group">
        <div class="col-md-6 col-xs-6">
          <%= f.label :password %><br />
        </div>
        <div class="col-md-offset-1 col-md-4 col-xs-5 text-right">
          <%= link_to 'Forgot password?', send("new_#{type}_password_path") if type != 'admin'%>
        </div>
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Log in", class: "btn btn-lg btn-default"%>
      </div>
    <% end %>
    <br />
    <div class="text-center sign-up-link">
      <%= link_to "Don't have an account? Join now.", new_shopper_registration_path %>
    </div>
  </div>
</div>