config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'

  get '/about'            =>  'static_pages#about'
  get '/retailer_info'    =>  'static_pages#retailer_info'
  get '/experience'       =>  'static_pages#experience'
  get '/decal'            =>  'static_pages#decal'
  get '/relaunch'         =>  'static_pages#relaunch'
  get '/join_confirmation'=>  'static_pages#join_confirmation'
  get '/confirmation_required'  => 'static_pages#confirmation_required'

  post 'swipe_styles/invite'    => 'swipe_styles#invite'
  get 'swipe_styles/new'        => 'swipe_styles#new'
  get 'swipe_styles/results'    => 'swipe_styles#results'
  post 'swipe_styles/like'      => 'swipe_styles#like'
  post 'swipe_styles/complete'  => 'swipe_styles#complete'
  delete 'swipe_styles/destroy' => 'swipe_styles#destroy'
  post 'swipe_styles/update_matches' => 'swipe_styles#update_matches'
  post 'swipe_styles/update_style_needs' => 'swipe_styles#update_style_needs'

  resources :share_quizzes, param: :name, only: [:show]

  namespace :webhooks do
    get 'mailchimp/subscribe'  => 'mailchimp_importer#validate'
    post 'mailchimp/subscribe' => 'mailchimp_importer#subscribe'
  end

  namespace :blog do
    resources :articles, path: '', only: [:index, :show]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  scope module: 'users' do
    resources :users, only: [] do
      collection do
        get :shoppers
      end
    end
  end

  resources :style_profiles, only: [:edit, :update, :new, :create] do
    collection do
      post :quickstart
    end
  end

  resources :retailers, only: [:show, :index, :new, :create] do
    member do
      get 'scheduled_availabilities'
      get 'enable_available_dates'
      get 'enable_available_times'
      get 'show_drop_in_location'
      get 'press_kit'
    end
  end

  resources :drop_ins, only: [:create, :update, :destroy] do
    member do
      patch :cancel
    end
    collection do
      get :upcoming
    end
  end

  resources :drop_in_availabilities, only: [:create, :update] do
    collection do
      get :personal
    end
  end

  get 'drop_in_availabilities/apply_form' => 'drop_in_availabilities#apply_form'

  resources :reports, only: [:new, :create]

  resources :retailer_referrals, only: [:create]

end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
  include ImageName
  include StatusLive
  include FeedSummary

  has_one :user, dependent: :destroy

  belongs_to :body_shape
  belongs_to :look
  belongs_to :primary_look, class_name: "Look"
  belongs_to :location
  belongs_to :top_fit
  belongs_to :bottom_fit
  has_and_belongs_to_many :special_considerations
  has_one :online_presence, dependent: :destroy
  has_many :drop_in_availabilities, dependent: :destroy
  has_many :drop_ins, dependent: :destroy

  accepts_nested_attributes_for :online_presence

  validates :name, presence: true, length: { maximum: 50 } 
  validates :description, presence: true, length: { maximum: 500 }
  validates :location_id, presence: true
  validates :size_range, presence: true
  validates :price_index, presence: true
  validates :quote, presence: true, length: { maximum: 100 }

  MAX_PRICE_RANGE_INDEX = 4
  GENERIC_SIZE_REGEX = /(X*S)|M|(X*L)/
  ORDERED_SIZES = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL']

  def self.showcase
    where(status: 1).where("above_fold_image <> ''")
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def available_for_drop_in? datetime
    drop_in_availabilities.order('created_at DESC').each do |availability|
      if availability.covers_datetime? datetime
        concurrent_drop_ins = drop_ins.overlapping(datetime, datetime.advance(minutes: 30))
        if concurrent_drop_ins.count >= availability.bandwidth
          return false
        end
        return true
      end
    end

    return false
  end

  def get_available_drop_in_dates format=:integer_array, 
                                  start_day=Time.zone.today.at_beginning_of_month,
                                  end_day=Time.zone.today.at_end_of_month

    ret = []
    current_day = start_day
    while(current_day <= end_day) do
      unless get_available_drop_in_times(current_day.to_s).empty?
        case format
        when :integer_array
          ret << [current_day.year, 
                  current_day.month - 1, 
                  current_day.day]
        when :date_string
          ret << current_day.strftime("%Y-%m-%d")
        else
        end
      end

      current_day = current_day.advance(days: 1)
    end
    ret
  end

  def get_drop_in_location date_string
    availability = get_relevant_availability date_string 
    return nil if availability.nil?
    availability.location
  end

  def get_available_drop_in_times date_string
    ret = []
    parsed_date = Time.zone.parse(date_string).to_date
    availability = get_relevant_availability date_string 
    return ret if availability.nil?

    start_time, end_time = availability.applied_start_and_end_times(parsed_date)

    first_time_slot = start_time
    if first_time_slot < Time.zone.now
        buffer = Time.zone.now.advance(minutes: 30)
      if buffer.min < 30
        first_time_slot = buffer.change(min: 30)
      else
        first_time_slot = buffer.change(hour: (buffer.hour + 1))
      end
    end

    while (first_time_slot < end_time) do
      concurrent_drop_ins = self.drop_ins.overlapping(first_time_slot, first_time_slot.advance(minutes: 30))

      unless concurrent_drop_ins.count >= availability.bandwidth
        time_string = first_time_slot.strftime("%-H:%-M")
        ret << time_string.split(':').map{|v| v.to_i}
      end

      first_time_slot = first_time_slot.advance(minutes: 30)
    end

    ret
  end

  def get_relevant_availability date_string
    parsed_date = Time.zone.parse(date_string).to_date
    drop_in_availabilities.order('created_at DESC').find{|a| a.covers_date? parsed_date }
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  before_filter :go_to_relaunch, :only => [:index]
  before_filter :authenticate_user!, only: [:new, :create, :press_kit]
  before_filter :correct_retail_user, only: [:press_kit]
  before_filter :authenticate_admin_user!, only: [:new, :create]

  def show
    @retailer = Retailer.find(params[:id])
    attempted_booking = retrieve_signed_out_booking
    if attempted_booking && user_signed_in?
      @drop_in = current_user.drop_ins.build(attempted_booking)
    end
  end

  def index
    @retailers = Retailer.all_live
  end

  def new
    @retailer = Retailer.new
  end

  def create
    @retailer = Retailer.new(retailer_params)
    if @retailer.save
      flash[:success] = "Retailer created"
      redirect_to retailers_path
    else
      render 'new'
    end
  end

  def scheduled_availabilities
    @available_dates = Retailer.find(params[:id])
                        .get_available_drop_in_dates(:date_string, 
                                                     Time.zone.parse(params[:start]).to_date,
                                                     Time.zone.parse(params[:end]).to_date)
    respond_to do |format|
      format.json {}
    end
  end

  def enable_available_dates
    start_date = Date.current
    end_date = Date.current.advance(months: 2)
    @available_dates = Retailer.find(params[:id])
                               .get_available_drop_in_dates(:integer_array,
                                                            start_date,
                                                            end_date)
    respond_to do |format|
      format.js {}
    end
  end

  def enable_available_times
    @available_times = Retailer.find(params[:id])
                               .get_available_drop_in_times(params[:date])
    respond_to do |format|
      format.js {}
    end
  end

  def show_drop_in_location
    @location = Retailer.find(params[:id])
                        .get_drop_in_location(params[:date]).stringify
    respond_to do |format|
      format.js {}
    end
  end

  def press_kit
    @retailer = Retailer.find(params[:id])
  end

  private
    def retailer_params
      params.require(:retailer).permit(:name, :location_id, :description, 
                      :for_petite, :for_tall, :for_full_figured,
                      special_consideration_ids: [], top_size_ids: [], 
                      bottom_size_ids: [], dress_size_ids: [],
                      price_range_attributes: [:top_min_price, :top_max_price,
                                               :bottom_min_price, :bottom_max_price,
                                               :dress_min_price, :dress_max_price],
                      online_presence_attributes: [:web_link, :facebook_link, 
                                                   :instagram_link, :twitter_link])
    end

    def correct_retail_user
      @retailer = Retailer.find(params[:id])
      if retailer_signed_in?
        redirect_to root_url unless @retailer == current_user.retailer
      end
    end
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_online_presence.html.erb
<% unless links.web_link.blank? %>
    <div class="col-xs-2">
      <h3>
        <a href="<%= links.web_link%>" target="_blank">
          <i class="fa fa-link"></i>
        </a>
      </h3>
    </div>
<% end %>

<% unless links.facebook_link.blank? %>
    <div class="col-xs-2">
      <h3>
        <a href="<%= links.facebook_link%>" target="_blank">
          <i class="fa fa-facebook"></i>
        </a>
      </h3>
    </div>
<% end %>

<% unless links.twitter_link.blank? %>
    <div class="col-xs-2">
      <h3>
        <a href="<%= links.twitter_link%>" target="_blank">
          <i class="fa fa-twitter"></i>
        </a>
      </h3>
    </div>
<% end %>

<% unless links.instagram_link.blank? %>
    <div class="col-xs-2">
      <h3>
        <a href="<%= links.instagram_link%>" target="_blank">
          <i class="fa fa-instagram"></i>
        </a>
      </h3>
    </div>
<% end %>

app/views/retailers/_retailer.html.erb
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 boutique-item">
      <a href="<%= retailer_path retailer%>">
      <div class="cover-photo">
        <%= cl_image_tag(retailer.cover_photo, width: 800, height: 400,
                         crop: :thumb, :gravity=>:north, class: 'img-responsive') %>
      </div>
      <div class="boutique-details">
        <div class="col-xs-12 contents">
          <div class="col-xs-12">
            <%= cl_image_tag(retailer.logo, width: 150, height: 150,
                             crop: :thumb, class: 'img-responsive center-block') %>
          </div>
          <div class="col-xs-12 text-center">
            <h4><%= StreetAddress::US.parse(retailer.location.address) %></h4>
          </div>
          <div class="col-md-4 col-xs-12 text-center"><h4><%= retailer.size_range %></h4></div>
          <div class="col-md-4 col-md-offset-4 col-xs-12 text-center">
            <h4>
              <% retailer.price_index.times do %>
                  <i class="fa fa-tag"></i>
              <% end %>
            </h4>
          </div>
        </div>
      </div>
      </a>
    </div>
  </div>
  <div class="boutique-title row">
    <div class="col-xs-8 col-xs-offset-2">
      <a href="<%= retailer_path retailer%>">
      <h3><%= retailer.name %></h3>
      <h4>
        <%= StreetAddress::US.parse(retailer.location.address).city %>,
        <%= StreetAddress::US.parse(retailer.location.address).state %>
      </h4>
      </a>
    </div>
  </div>

app/views/retailers/_sample_image_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @retailer.sample_photos.size.times do |count| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= count.to_s %>"
            class="<%= 'active' if count == 0%>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @retailer.sample_photos.each_with_index do |image, idx| %>
        <div class="item <%= 'active' if idx == 0%>">
          <%= cl_image_tag(image, width: 800, height: 600, crop: :thumb, alt: 'sample image') %>
        </div>
    <% end %>
  </div>
</div>

app/views/retailers/enable_available_dates.js.erb
var $input = $('.datepicker').pickadate()
var picker = $input.pickadate('picker')

picker.set('disable', <%= [true] + @available_dates %>)

app/views/retailers/enable_available_times.js.erb
var $timeInput = $('.timepicker').pickatime()
var picker = $timeInput.pickatime('picker')

picker.set('disable', <%= [true] + @available_times %>)

app/views/retailers/index.html.erb
<%= provide(:title, 'Boutiques') %>
<%= render "shared/header" %>

<div class="boutiques container">
  <div class="intro">
    <div class="text-center">
      <h1>Check out our Partner Boutiques</h1>
      <h2>Stay tuned as we continue to grow</h2>
      <br /><br />
      <h3><a href="#" id="show-store-referral-form">Know a good boutique for OpenStile?</a></h3>
    </div>
    <div class="col-xs-6 col-xs-offset-3 store-referral-form">
      <div class="form-errors"></div>
      <%= form_for(@referral || RetailerReferral.new, remote: true, html: {class: "form-horizontal"}) do |f| %>
          <div class="form-group">
            <%= f.label :referrer_name, 'Your name', class: "control-label" %>
            <%= f.text_field :referrer_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :referrer_email, 'Your email', class: "control-label" %>
            <%= f.text_field :referrer_email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :store_name, 'Store name', class: "control-label" %>
            <%= f.text_field :store_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :website, 'Link to store', class: "control-label" %>
            <div class="input-group">
              <span class="input-group-addon">http://</span>
              <%= f.text_field :website, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :contact_name, 'Store contact name', class: "control-label" %>
            <%= f.text_field :contact_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :contact_email, 'Store contact email', class: "control-label" %>
            <%= f.text_field :contact_email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Submit', class: "btn btn-default" %>
          </div>
      <% end %>
    </div>
  </div>

  <% @retailers.each do |retailer| %>
      <%= render 'retailer', retailer: retailer %>
  <% end %>

</div>

app/views/retailers/new.html.erb
<%= provide(:title, 'Create Retailer') %>
<%= render "shared/header" %>

<div class="block">
  <div class="container">
    <div class="row text-center">
      <h2>Enter retailer information</h2>
    </div>
    <br /><br />
    <div class="row">
      <div class="col-md-6 col-xs-6 col-md-offset-3 col-xs-offset-3">
        <%= form_for @retailer, class: "form-horizontal" do |f| %>
          <%= render 'shared/error_messages', object: @retailer %>

          <%= f.label :name %>
          <%= f.text_field :name %>

          <%= f.label :owner_name %>
          <%= f.text_field :owner_name %>

          <%= f.label :phone_number %>
          <%= f.text_field :phone_number %>

          <%= f.label :location_id %>
          <%= f.select :location_id, Location.all.map{|l| [l.address, l.id]},
                                    {prompt: true} %>

          <%= f.label :description %>
          <%= f.text_area :description %>

          <%= f.fields_for :online_presence, @retailer.build_online_presence do |op_form| %>
            <%= op_form.label :web_link, 'Website' %>
            <%= op_form.text_field :web_link %>

            <%= op_form.label :facebook_link, 'Facebook' %>
            <%= op_form.text_field :facebook_link %>

            <%= op_form.label :instagram_link, 'Instagram' %>
            <%= op_form.text_field :instagram_link %>

            <%= op_form.label :twitter_link, 'Twitter' %>
            <%= op_form.text_field :twitter_link %>
          <% end %>

          <div class="special-considerations">
            <div class="options row">
              <div class="col-md-offest-1 col-xs-offset-1">
                <%= f.collection_check_boxes(:special_consideration_ids,
                              SpecialConsideration.all, :id, :name) do |builder| %>
                  <div class="single-checkbox">
                    <%= builder.label(class: "checkbox-inline col-md-3 col-xs-3") {
                      builder.check_box(class: "col-md-2 col-xs-2") + builder.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <br />
          <%= f.fields_for :price_range, @retailer.build_price_range do |pr_form| %>
            <%= pr_form.label :top_min_price %>
            <%= pr_form.text_field :top_min_price %>
            <%= pr_form.label :top_max_price %>
            <%= pr_form.text_field :top_max_price %>
            <%= pr_form.label :bottom_min_price %>
            <%= pr_form.text_field :bottom_min_price %>
            <%= pr_form.label :bottom_max_price %>
            <%= pr_form.text_field :bottom_max_price %>
            <%= pr_form.label :dress_min_price %>
            <%= pr_form.text_field :dress_min_price %>
            <%= pr_form.label :dress_max_price %>
            <%= pr_form.text_field :dress_max_price %>
          <% end %>

          <h4>Top Sizes: </h4>
          <div class="top-sizes">
            <div class="options row">
              <div class="col-md-offest-1 col-xs-offset-1">
                <%= f.collection_check_boxes(:top_size_ids,
                                TopSize.all, :id, :name) do |builder| %>
                  <div class="single-checkbox">
                    <%= builder.label(class: "checkbox-inline col-md-3 col-xs-3") {
                      builder.check_box(class: "col-md-2 col-xs-2") + builder.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <h4>Bottom Sizes: </h4>
          <div class="bottom-sizes">
            <div class="options row">
              <div class="col-md-offest-1 col-xs-offset-1">
                <%= f.collection_check_boxes(:bottom_size_ids,
                                BottomSize.all, :id, :name) do |builder| %>
                  <div class="single-checkbox">
                    <%= builder.label(class: "checkbox-inline col-md-3 col-xs-3") {
                      builder.check_box(class: "col-md-2 col-xs-2") + builder.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <h4>Dress Sizes: </h4>
          <div class="dress-sizes">
            <div class="options row">
              <div class="col-md-offest-1 col-xs-offset-1">
                <%= f.collection_check_boxes(:dress_size_ids,
                                DressSize.all, :id, :name) do |builder| %>
                  <div class="single-checkbox">
                    <%= builder.label(class: "checkbox-inline col-md-3 col-xs-3") {
                      builder.check_box(class: "col-md-2 col-xs-2") + builder.text } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <%= f.label :for_petite %>
          <%= f.check_box :for_petite %>

          <%= f.label :for_tall %>
          <%= f.check_box :for_tall %>

          <%= f.label :for_full_figured %>
          <%= f.check_box :for_full_figured %>

          <%= f.submit 'Add' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/retailers/press_kit.html.erb
<%= provide(:title, 'Press Kit') %>
<%= render "shared/header" %>

<div class="press-kit container">
  <div class="row intro text-center">
    <h1>Tell everyone <%= @retailer.name %> is on OpenStile!</h1>
  </div>
  <div class="row share-cards">
    <div class="col-sm-6 col-md-3 text-center">
      <div class="single">
        <h3>Share on Twitter</h3><br />
        <a class="twitter-share-button"
           href="https://twitter.com/share"
           data-size="small"
           data-url="<%= retailer_url @retailer %>"
           data-via="OpenStile"
           data-hashtags="personalStyling,shopLocal"
           data-text="We're on OpenStile. Book a free styling today!">
          Tweet
        </a>
      </div>
    </div>
    <div class="col-sm-6 col-md-3 text-center">
      <div class="single">
        <h3>Share on Facebook</h3>
        <br />
        <div class="fb-share-button" data-href="<%= retailer_url @retailer %>" data-layout="button"></div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3 text-center">
      <div class="single">
        <h3>Download share image</h3>
        <br />
        <h3><a href="http://res.cloudinary.com/openstile/image/upload/v1449024965/were_on_openstile.jpg">
          <i class="fa fa-picture-o"></i></a></h3>
      </div>
    </div>
    <div class="col-sm-6 col-md-3 text-center">
      <div class="single">
        <h3>Embed on site</h3>
        <br />
        <h3><a id="show-embed-code" href="#"><i class="fa fa-code"></i></a></h3>
      </div>
    </div>
  </div>
  <div class="row embed-code">
    <hr />
    <h3 class="text-center">Embed an OpenStile banner on your website</h3><br /><br />
    <h4>This is what your banner will look like. Clicking on it will take users to your OpenStile page.</h4>
    <iframe width="250" height="250" src="<%= decal_path retailer_id: @retailer.id %>" scrolling="auto" frameborder="0" allowtransparency="true" style="border:none;"></iframe>
    <h4>Place the code for the banner wherever you want the banner to appear on your page.</h4>
    <div class="col-xs-8">
      <pre>&lt;iframe width="250" height="250" src="http://openstile.com/decal?retailer_id=<%= @retailer.id %>" scrolling="auto" frameborder="0" allowtransparency="true" style="border:none;"&gt;&lt;/iframe&gt;</pre>
    </div>
  </div>
</div>

app/views/retailers/scheduled_availabilities.json.erb
<%= @available_dates.map{|v| {"start"=>v, "title"=>"Accepting drop-ins"}}.to_json.html_safe %>

app/views/retailers/show.html.erb
<% provide(:title, @retailer.name) %>

<%= render "shared/header" %>

<div class="boutique-page container">
  <div class="row intro">
    <div class="col-xs-6">
      <%= render 'retailers/sample_image_carousel' %>
    </div>
    <div class="col-xs-6 text-center">
      <h2><%= @retailer.name %></h2>
      <h3 class="neighborhood"><%= @retailer.location.neighborhood %></h3>
      <h1 class="store-quote"><%= @retailer.quote %></h1>
      <a href="#" class="btn try-today opn-btn" id="show-booking-form">Book FREE Styling</a>
    </div>
  </div>
  <div class="row details">
    <hr />
    <div class="col-xs-12 col-md-6 text-justify section">
      <div class="col-xs-6 col-md-4">
        <h3>Owner: </h3>
        <h3>Address: </h3>
        <h3>Sizes: </h3>
        <h3>Price range: </h3>
      </div>
      <div class="col-xs-6 col-md-8">
        <h3><%= "#{@retailer.user.first_name} #{@retailer.user.last_name}"%></h3>
        <h3><%= StreetAddress::US.parse(@retailer.location.address) %></h3>
        <h3><%= @retailer.size_range%></h3>
        <h3>
          <% Retailer::MAX_PRICE_RANGE_INDEX.times do |idx| %>
              <i class="fa fa-tag <%= 'activated' if idx + 1 <= @retailer.price_index %>"></i>
          <% end %>
        </h3>
      </div>
    </div>
    <div class="col-xs-12 col-md-6 text-justify section">
      <h3><%= @retailer.description %></h3>
      <%= render 'retailers/online_presence', links: @retailer.online_presence unless @retailer.online_presence.nil?%>
    </div>
  </div>
  <div class="row book-styling">
    <hr />
    <%= render 'shared/schedule_drop_in', retailer: @retailer, for_retailer: true %>
  </div>
</div>

<% set_meta_tags og: {
                         locale:        'en_US',
                         type:          'website',
                         title:         'OpenStile | Hand-picked style at your favorite local boutiques',
                         description:   "Book a FREE personal styling session with #{@retailer.name} today!",
                         url:           retailer_url(@retailer),
                         image:         cloudinary_url_internal(@retailer.sample_photos.first)
                 }
%>

<% set_meta_tags twitter: {
                         card: "summary_large_image",
                         site: "@OpenStile"
                 }
%>

app/views/retailers/show_drop_in_location.js.erb
$('.schedule #location').append('<h4>This drop in will take place at <%= @location %></h4>');